polyst:
  species:
    9606:
      common-name: Human
      scientific-name: Homo sapiens
      release: '2019_10'
      extra:
      id: 9606
      subdirectory: d9606
      active: true
      disorder-prediction: true # Do the protein files contain IUpred and ESpritz columns?
      index-group: 1
    10090:
      common-name: Mouse
      scientific-name: Mus musculus
      release: '2019_09'
      extra:
      id: 10090
      subdirectory: d10090
      active: true
      disorder-prediction: false
      index-group: 2
    9823:
      common-name: Wild boar
      scientific-name: Sus scrofa
      release: '2019_09'
      extra:
      id: 9823
      subdirectory: d9823
      active: true
      disorder-prediction: false
      index-group: 2
    9913:
      common-name: Cow
      scientific-name: Bos taurus
      release: '2019_09'
      extra:
      id: 9913
      subdirectory: d9913
      active: true
      disorder-prediction: false
      index-group: 2
    9940:
      common-name: Sheep
      scientific-name: Ovis aries
      release: '2019_09'
      extra:
      id: 9940
      subdirectory: d9940
      active: true
      disorder-prediction: false
      index-group: 2
    7955:
      common-name: Zebrafish
      scientific-name: Danio rerio
      release: '2019_09'
      extra:
      id: 7955
      subdirectory: d7955
      active: true
      disorder-prediction: false
      index-group: 2
    9031:
      common-name: Chicken
      scientific-name: Gallus gallus
      release: '2019_09'
      extra:
      id: 9031
      subdirectory: d9031
      active: true
      disorder-prediction: false
      index-group: 2
    9443:
      common-name: Primates
      scientific-name: Primates
      release: '2019_10'
      extra:
      id: 9443
      subdirectory: d9443
      active: true
      disorder-prediction: false
      index-group: 3
    40674:
      common-name: Mammals
      scientific-name: Mammalia
      release: '2019_10'
      extra: excluding Primates, Mouse, Wild boar, Cow, and Sheep
      id: 40674
      subdirectory: d40674
      active: true
      disorder-prediction: false
      index-group: 3
    7742:
      common-name: Vertebrates
      scientific-name: Vertebrata
      release: '2019_10'
      extra: excluding Mammalia, Zebrafish, and Chicken
      id: 7742
      subdirectory: d7742
      active: true
      disorder-prediction: false
      index-group: 3
    3635:
      common-name: Cotton
      scientific-name: Gossypium hirsutum
      release: '2020_01'
      extra:
      id: 3635
      subdirectory: d3635
      active: true
      disorder-prediction: false
      index-group: 4
    3847:
      common-name: Soybean
      scientific-name: Glycine max
      release: '2020_01'
      extra:
      id: 3847
      subdirectory: d3847
      active: true
      disorder-prediction: false
      index-group: 4
    3879:
      common-name: Alfalfa
      scientific-name: Medicago sativa
      release: '2020_01'
      extra:
      id: 3879
      subdirectory: d3879
      active: true
      disorder-prediction: false
      index-group: 4
    4081:
      common-name: Tomato
      scientific-name: Solanum lycopersicum
      release: '2020_01'
      extra:
      id: 4081
      subdirectory: d4081
      active: true
      disorder-prediction: false
      index-group: 4
    4113:
      common-name: Potato
      scientific-name: Solanum tuberosum
      release: '2020_01'
      extra:
      id: 4113
      subdirectory: d4113
      active: true
      disorder-prediction: false
      index-group: 4
    4513:
      common-name: Barley
      scientific-name: Hordeum vulgare
      release: '2020_01'
      extra:
      id: 4513
      subdirectory: d4513
      active: true
      disorder-prediction: false
      index-group: 4
    4530:
      common-name: Rice
      scientific-name: Oryza sativa
      release: '2020_01'
      extra:
      id: 4530
      subdirectory: d4530
      active: true
      disorder-prediction: false
      index-group: 4
    4565:
      common-name: Wheat
      scientific-name: Triticum aestivum
      release: '2020_01'
      extra:
      id: 4565
      subdirectory: d4565
      active: true
      disorder-prediction: false
      index-group: 4
    4577:
      common-name: Maize
      scientific-name: Zea mays
      release: '2020_01'
      extra:
      id: 4577
      subdirectory: d4577
      active: true
      disorder-prediction: false
      index-group: 4
    381124:
      common-name: Corn
      scientific-name: Zea mays subsp. mays
      release: '2020_01'
      extra:
      id: 381124
      subdirectory: d381124
      active: true
      disorder-prediction: false
      index-group: 4
