polyst:
  species:
    9606:
      common-name: Human
      scientific-name: Homo sapiens
      updated: '2019-10'
      extra:
      id: 9606
      subdirectory: d9606
      active: true
      disorder-prediction: true # Do the protein files contain IUpred and ESpritz columns?
      index-group: 1
    10090:
      common-name: Mouse
      scientific-name: Mus musculus
      updated: '2019-09'
      extra:
      id: 10090
      subdirectory: d10090
      active: true
      disorder-prediction: false
      index-group: 2
    9823:
      common-name: Wild boar
      scientific-name: Sus scrofa
      updated: '2019-09'
      extra:
      id: 9823
      subdirectory: d9823
      active: true
      disorder-prediction: false
      index-group: 2
    9913:
      common-name: Cow
      scientific-name: Bos taurus
      updated: '2019-09'
      extra:
      id: 9913
      subdirectory: d9913
      active: true
      disorder-prediction: false
      index-group: 2
    9940:
      common-name: Sheep
      scientific-name: Ovis aries
      updated: '2019-09'
      extra:
      id: 9940
      subdirectory: d9940
      active: true
      disorder-prediction: false
      index-group: 2
    7955:
      common-name: Zebrafish
      scientific-name: Danio rerio
      updated: '2019-09'
      extra:
      id: 7955
      subdirectory: d7955
      active: true
      disorder-prediction: false
      index-group: 2
    9031:
      common-name: Chicken
      scientific-name: Gallus gallus
      updated: '2019-09'
      extra:
      id: 9031
      subdirectory: d9031
      active: true
      disorder-prediction: false
      index-group: 2
    9443:
      common-name: Primates
      scientific-name: Primates
      updated: '2019-10'
      extra:
      id: 9443
      subdirectory: d9443
      active: true
      disorder-prediction: false
      index-group: 3
    40674:
      common-name: Mammals
      scientific-name: Mammalia
      updated: '2019-10'
      extra: excluding Primates, Mouse, Wild boar, Cow, and Sheep
      id: 40674
      subdirectory: d40674
      active: true
      disorder-prediction: false
      index-group: 3
    7742:
      common-name: Vertebrates
      scientific-name: Vertebrata
      updated: '2019-10'
      extra: excluding Mammalia, Zebrafish, and Chicken
      id: 7742
      subdirectory: d7742
      active: true
      disorder-prediction: false
      index-group: 3
